### ISSUE TITLE
Pop-Apple Question 🍎

### ISSUE THREAD

**Issue by Pop-Apple** [Korozin/JGecko_Remade-in_Python#1]
### It's a very cute PyGecko 🥰
<p>
   <img src="https://user-images.githubusercontent.com/101918076/192754037-820bf3db-9a9f-4bd8-b3c0-776b3d066c00.png" width="500" height="300">
</p>

## Question
Hello Korozin, 
Sorry to keep bothering you 😭
I have a question.  
`PySimpleGUI` is Will it work on [Pydroid](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3&hl=en&gl=US) ?

**Comment by Korozin** [comment]
Yes actually, this was just an edited version of AppGecko which was developed with mobile devices in mind. So yes it will work on PyDroid :)

**Comment by Korozin** [comment]
instagram : korozin_alt
gmail : mammothasdfman@gmail.com

**Comment by Pop-Apple** [comment]
I see
Thank you for your cooperation. 😍
This issue is `closed`
